
title = "Vishus Blog"

# The URL the site will be built for
base_url = "https://vishusandy.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "vishus"
extra_syntaxes_and_themes = ["syntax"]

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[extra]
katex_enable = true      # include files for rendering math content
katex_auto_render = true # automatically render math content
enable_top_link = true   # if true show a link to the top of the page in the header

[[extra.links]]
text = "Links"
url = "/pages/links"
static_url = false   # if true the url is not a local markdown file
new_window = false

[[extra.links]]
text = "<i class=\"link-icon fa-brands fa-github\" alt=\"Go to my GitHub profile\" title=\"My GitGub\"></i>"
url = "https://github.com/vishusandy"
# if true the url is not a local markdown file
static_url = true
new_window = true

[[extra.links]]
text = "<i class=\"link-icon fa-brands fa-mastodon\" alt=\"Go to my Mastodon profile\" title=\"My Mastodon profile\"></i>"
url = "https://social.linux.pizza/@vishus"
# if true the url is not a local markdown file
static_url = true
# new window will be default override the rel attribute
new_window = false
# extra attributes - add the rel="me" for mastodon
attribues = "target=\"_blank\" rel=\"me noreferrer noopener\""
