
title = "Vishus Blog"

# The URL the site will be built for
base_url = "https://vishusandy.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Use the included `syntax/vishus.tmTheme` for syntax highlighting
highlight_theme = "vishus"
extra_syntaxes_and_themes = ["syntax"]

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra]
katex_enable = true                             # include files for rendering math content
katex_auto_render = true                        # automatically render math content
enable_top_link = true                          # if true show a link to the top of the page in the header
footer_copyright = "&copy; 2022 Andrew Prindle"

# when an updated date is specified you can automatically show a link to the git repo to show the file's history
# leave blank to disable
git_file_changes = "https://github.com/vishusandy/vishusandy.github.io/commits/main/content"

# Adds a "Links" link in the header
[[extra.header_links]]
text = "Links"
url = "/pages/links" # if this is not present, or blank, it will just show the text with no link
# link options
static_url = false # if true the url is not a local markdown file
new_window = false # whether to open the link in a new window
attributes = ""    # custom attributes to add to the <a> tag
page_only = false  # whether this link should only be shown on pages or sections too

[[extra.header_links]]
text = "<i class=\"link-icon fa-brands fa-mastodon\" alt=\"Go to my Mastodon profile\" title=\"My Mastodon profile\"></i>"
url = "https://social.linux.pizza/@vishus"
# liink options
static_url = true  # this is a static url since it's not a link produced by Zola
new_window = false # `new_window=true` would override the `rel="me"` attribute; use `attributes` to open the link in a new window
# extra attributes - add the rel="me" for mastodon
attribues = "target=\"_blank\" rel=\"me noreferrer noopener\" aria-label=\"Open Mastodon profile in a new window\""

[[extra.header_links]]
text = "<i class=\"link-icon fa-brands fa-github\" alt=\"Go to my GitHub profile\" title=\"My GitGub\"></i>"
url = "https://github.com/vishusandy"
# this is a static url since it's not a link produced by Zola
static_url = true
new_window = true
attributes = "aria-label=\"Open Github profile in a new window\""


[[extra.footer_links]]
url = ""
text = "&copy; 2023 Andrew Prindle"
static_url = true                   # if true the url is not a local markdown file
new_window = true                   # whether to open the link in a new window
attributes = ""                     # custom attributes to add to the <a> tag
pages_only = true

[[extra.footer_links]]
url = "https://github.com/vishusandy/vishusandy.github.io"
text = "Source"
static_url = true                                          # if true the url is not a local markdown file
new_window = true                                          # whether to open the link in a new window
attributes = ""                                            # custom attributes to add to the <a> tag
pages_only = true
